/* eslint-disable */
export const activities = [{id:123	,	name: 'Development'},
  {id:124	,	name: 'Support'},
  {id:125	,	name: 'Enhancement'},
  {id:126	,	name: 'QA'},
  {id:127	,	name: 'REM Support'},
  {id:128	,	name: 'JH PMO Advanced Delivery Track'},
  {id:129	,	name: 'Analysis'},
  {id:130	,	name: 'Business Analysis Development Program Time Allocation'},
  {id:131	,	name: 'Cast Iron - Disaster Recovery'},
  {id:132	,	name: 'DB Access and ID support'},
  {id:133	,	name: 'DB Incident Management'},
  {id:134	,	name: 'Fix and Retest'},
  {id:135	,	name: 'IRM - Access Reviews & Approvals'},
  {id:136	,	name: 'IAM - IIQ Integrations'},
  {id:137	,	name: 'IRM - Internal Audit Oversight'},
  {id:138	,	name: 'PMO - Audit'},
  {id:139	,	name: 'Planning'},
  {id:140	,	name: 'PMO JH PMO'},
  {id:141	,	name: 'PS - RPS Support'},
  {id:142	,	name: 'QA Effort - Change Control'},
  {id:143	,	name: 'QA Planning - Estimates'},
  {id:144	,	name: 'QA Warranty'},
  {id:145	,	name: 'Release coordination'},
  {id:146	,	name: 'REM Build and Deployment'},
  {id:147	,	name: 'SOA - Development'},
  {id:148	,	name: 'SOA - Incidents (support)'},
  {id:149	,	name: 'SOA – Testing Support'},
  {id:150	,	name: 'TRS - ETL Development'},
  {id:151	,	name: 'TRS - Research'},
  {id:152	,	name: 'USI DM - Project Intake'},
  {id:153	,	name: 'WMD - Incident Management'},
  {id:154	,	name: 'WMD - Technical Consulting'},
  {id:155	,	name: 'WMD TIBCO Development'},
  {id:156	,	name: 'Training'},
  {id:157	,	name: 'Tech Lead'},
  {id:158	,	name: 'RPS - Azure Support/Monitoring'},
  {id:159	,	name: 'QA functional testing'},
  {id:160	,	name: 'Project Manager'},
  {id:161	,	name: 'SOA - Analysis'},
  {id:162	,	name: 'USI - Compliance'}
]
